services:
  nanase-bot:
    container_name: nanase-bot
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_module
      - /app/.pnpm-store
