name: Check

on:
  pull_request:
  push:

jobs:
  check:
    name: ${{ matrix.command }}
    strategy:
      matrix:
        command:
          - typecheck
          - format:check
          - build
          # FIXME: fixが完了したらこのコメントアウトを外し、CIを有効化する。
          # - check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ${{ matrix.command }}

  docker-build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --pull --tag nanase-bot:ci .
